name = "EnergyModelsHydrogen"
uuid = "44855f8b-b147-4985-ac18-48817d03c548"
authors = ["Julian Straus <Julian.Straus@sintef.no>, Avinash Subramanian"]
version = "0.7.3"

[deps]
EnergyModelsBase = "5d7e687e-f956-46f3-9045-6f5a5fd49f50"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
TimeStruct = "f9ed5ce0-9f41-4eaa-96da-f38ab8df101c"

[weakdeps]
EnergyModelsInvestments = "fca3f8eb-b383-437d-8e7b-aac76bb2004f"

[extensions]
EMIExt = "EnergyModelsInvestments"

[compat]
EnergyModelsBase = "0.8.3"
EnergyModelsInvestments = "0.8"
JuMP = "1.5"
julia = "1.10"
TimeStruct = "0.9"